version: "2"
services:
  xl-deploy:
    image: xebialabs/xl-deploy:8.1
    container_name: xl-deploy
    ports:
     - "4516:4516"
    volumes:
     - ~/XebiaLabs/xl-deploy-server/conf:/opt/xl-deploy-server/conf
     - ~/XebiaLabs/xl-deploy-server/ext:/opt/xl-deploy-server/ext
     - ~/XebiaLabs/xl-deploy-server/hotfix/lib:/opt/xl-deploy-server/hotfix/lib
     - ~/XebiaLabs/xl-deploy-server/hotfix/plugins:/opt/xl-deploy-server/hotfix/plugins
     - ~/XebiaLabs/xl-deploy-server/plugins:/opt/xl-deploy-server/plugins
     - ~/XebiaLabs/xl-deploy-server/repository:/opt/xl-deploy-server/repository
    environment:
     - ADMIN_PASSWORD=admin

  xl-release:
    image: xebialabs/xl-release:8.1
    container_name: xl-release
    ports:
     - "5516:5516"
    links:
     - xl-deploy
    volumes:
     - ~/XebiaLabs/xl-release-server/archive:/opt/xl-release-server/archive
     - ~/XebiaLabs/xl-release-server/conf:/opt/xl-release-server/conf
     - ~/XebiaLabs/xl-release-server/ext:/opt/xl-release-server/ext
     - ~/XebiaLabs/xl-release-server/hotfix/:/opt/xl-release-server/hotfix/
     - ~/XebiaLabs/xl-release-server/plugins:/opt/xl-release-server/plugins
     - ~/XebiaLabs/xl-release-server/repository:/opt/xl-release-server/repository
    environment:
     - ADMIN_PASSWORD=admin
